# Generated by Django 5.1.7 on 2025-03-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2020/07/07/11/45/coming-soon-5380230_1280.png', max_length=500),
        ),
    ]
