# Generated by Django 5.1.7 on 2025-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2017/02/16/02/54/coming-soon-2070393_1280.jpg', max_length=500),
        ),
    ]
